<a href="https://colab.research.google.com/github/Hazuna227/221230039-Pengantar-ML/blob/main/week-02/latihan_praktikum_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LATIHAN 2: OPERASI NUMPY UNTUK MACHINE LEARNING

In [1]:
import numpy as np

# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5  # Mean=5, Std=10

# =========================
# TODO 1: Z-score Normalization
# =========================
def z_score_normalization(data):
    """
    Normalisasi Z-score: (x - mean) / std
    Input: data (numpy array)
    Output: normalized data dengan mean=0, std=1
    """
    if data.size == 0:
        raise ValueError("Input data kosong")

    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)

    # Menghindari pembagian dengan 0
    std_corrected = np.where(std == 0, 1, std)

    normalized = (data - mean) / std_corrected
    return normalized

X_normalized = z_score_normalization(X)

# =========================
# TODO 2: Handle Outliers
# =========================
def handle_outliers(data, std_threshold=3):
    """
    Clip values di luar ±std_threshold
    Input: data (numpy array), std_threshold (default=3)
    Output: data dengan outlier di-clipping
    """
    if data.size == 0:
        raise ValueError("Input data kosong")

    # Hitung mean & std per kolom
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)

    upper_bound = mean + std_threshold * std
    lower_bound = mean - std_threshold * std

    # Clip semua nilai sesuai batas
    clipped = np.clip(data, lower_bound, upper_bound)
    return clipped

X_cleaned = handle_outliers(X_normalized)

# =========================
# TODO 3: One-hot Encoding
# =========================
def one_hot_encoding(labels):
    """
    Convert label kategorikal menjadi one-hot encoding
    Input: labels (1D numpy array)
    Output: 2D numpy array one-hot
    """
    if labels.size == 0:
        raise ValueError("Input labels kosong")

    n_classes = np.max(labels) + 1
    one_hot = np.eye(n_classes)[labels]
    return one_hot

labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)

# =========================
# TODO 4: Train-test Split Manual
# =========================
def train_test_split_numpy(X, y, test_size=0.2, random_seed=42):
    """
    Split dataset menjadi train dan test secara manual
    Input: X (features), y (labels), test_size (float 0-1)
    Output: X_train, X_test, y_train, y_test
    """
    if X.shape[0] != y.shape[0]:
        raise ValueError("Jumlah samples X dan y harus sama")
    if not (0 < test_size < 1):
        raise ValueError("test_size harus antara 0 dan 1")

    np.random.seed(random_seed)
    indices = np.random.permutation(X.shape[0])
    test_count = int(X.shape[0] * test_size)

    test_idx = indices[:test_count]
    train_idx = indices[test_count:]

    X_train = X[train_idx]
    X_test = X[test_idx]
    y_train = y[train_idx]
    y_test = y[test_idx]

    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split_numpy(X, np.random.randint(0, 3, 100))

# =========================
# Validasi hasil
# =========================
assert X_normalized.shape == X.shape, "Shape should remain same"
assert np.allclose(X_normalized.mean(), 0, atol=1e-10), "Mean should be ~0 after z-score"
assert np.allclose(X_normalized.std(), 1, atol=1e-10), "Std should be ~1 after z-score"

print("✅ NumPy operations completed")
print("X_normalized:\n", X_normalized[:5])
print("X_cleaned:\n", X_cleaned[:5])
print("One-hot labels:\n", one_hot_labels)


✅ NumPy operations completed
X_normalized:
 [[ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
 [-0.21141045  1.53420502  0.87977344 -0.62585547  0.53845484]
 [-0.46735006 -0.55422449  0.34303561 -2.13809665 -1.58578836]
 [-0.57771567 -1.1129603   0.41687036 -1.08519209 -1.2929218 ]
 [ 1.68601234 -0.30916828  0.16486193 -1.62640854 -0.47982667]]
X_cleaned:
 [[ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
 [-0.21141045  1.53420502  0.87977344 -0.62585547  0.53845484]
 [-0.46735006 -0.55422449  0.34303561 -2.13809665 -1.58578836]
 [-0.57771567 -1.1129603   0.41687036 -1.08519209 -1.2929218 ]
 [ 1.68601234 -0.30916828  0.16486193 -1.62640854 -0.47982667]]
One-hot labels:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
