<a href="https://colab.research.google.com/github/Hazuna227/221230039-Pengantar-ML/blob/main/week-02/latihan_praktikum_4_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LATIHAN 4: OPERASI PYTORCH UNTUK DEEP LEARNING

In [2]:
import torch

# =========================
# Simulasi batch data
# =========================
batch_size, n_features = 32, 10
torch.manual_seed(42)  # agar output reproducible
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)
bias = torch.randn(1)

# =========================
# Linear layer
# =========================
def linear_layer(X, W, b):
    return X @ W + b

output = linear_layer(X, weights, bias)

# =========================
# ReLU activation
# =========================
def relu_activation(tensor):
    return torch.maximum(tensor, torch.tensor(0.0))

activated = relu_activation(output)

# =========================
# Batch normalization
# =========================
def simple_batch_norm(tensor, epsilon=1e-5):
    mean = tensor.mean(dim=0, keepdim=True)
    std = tensor.std(dim=0, keepdim=True)
    return (tensor - mean) / (std + epsilon)

normalized = simple_batch_norm(X)

# =========================
# One-hot encoding
# =========================
def one_hot_pytorch(labels, num_classes):
    one_hot = torch.zeros(labels.size(0), num_classes)
    one_hot[torch.arange(labels.size(0)), labels] = 1
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)

# =========================
# Print output
# =========================
print("✅ Linear layer output (first 5 rows):\n", output[:5])
print("\n✅ ReLU activated output (first 5 rows):\n", activated[:5])
print("\n✅ Batch normalized X (first 5 rows):\n", normalized[:5])
print("\n✅ One-hot encoded labels:\n", one_hot)

# =========================
# Manual matrix multiplication
# =========================
def manual_matrix_multiply(A, B):
    m, n = A.shape
    n2, p = B.shape
    if n != n2:
        raise ValueError("Inner dimensions must match")
    C = torch.zeros(m, p)
    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]
    return C

# Test
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

print("\n✅ Manual matrix multiplication result:\n", manual_result)
print("\n✅ Torch.matmul result:\n", torch_result)

# =========================
# Assertions
# =========================
assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"
assert torch.allclose(manual_result, torch_result), "Manual multiplication incorrect"
print("\n✅ All checks passed")


✅ Linear layer output (first 5 rows):
 tensor([[ 5.5341],
        [-1.2201],
        [ 1.9464],
        [ 0.8760],
        [-5.2849]])

✅ ReLU activated output (first 5 rows):
 tensor([[5.5341],
        [0.0000],
        [1.9464],
        [0.8760],
        [0.0000]])

✅ Batch normalized X (first 5 rows):
 tensor([[ 2.2481,  1.1513,  1.1982, -2.1970,  0.8047, -1.4145, -0.1293, -2.2946,
         -0.6585,  1.7036],
        [-0.0680, -1.7929, -0.5556, -0.6701, -0.6846,  0.4437,  1.2857, -0.2846,
         -0.4262,  0.3183],
        [-0.4331,  0.7348,  1.0906,  1.5420,  1.4228,  0.9406,  0.4194,  1.7938,
         -0.1839, -0.1374],
        [ 0.0727,  0.5123, -1.2629, -0.9781, -0.1233,  1.3323,  0.1746, -0.6531,
          0.3060, -1.0727],
        [-1.2314,  0.6506, -0.7192, -0.7113, -1.2046,  1.7096, -1.1297, -0.7413,
         -0.8059, -0.9393]])

✅ One-hot encoded labels:
 tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [